export const karnatakaDlAddressChangeRoute = {
  serviceUrl: "https://sarathi.parivahan.gov.in/",
  sourceUrl: "https://parivahan.gov.in/en/faq/services-on-driver-license?page=0",
  checkedOn: "5 September 2026",
};

export const sarathiPaymentStatusRoute = {
  serviceUrl: "https://sarathi.parivahan.gov.in/",
  instructionsUrl: "https://sarathi.parivahan.gov.in/paymentscov/HELP.htm",
  checkedOn: "5 September 2026",
};

export const indianStatesAndUts = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi (NCT)",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;
